pub const OPCode = enum(u4) {
    MACHINE = 0,
    JUMP = 1,
    SUBROUTINE = 2,
    SKIP_EQ_IMM = 3,
    SKIP_NE_IMM = 4,
    SKIP_EQ = 5,
    LOAD = 6,
    ADD = 7,
    MATH = 8,
    SKIP_NE = 9,
    LOAD_I = 10,
    JUMP_OFFSET = 11,
    RAND = 12,
    DRAW = 13,
    SKIP_KEY = 14,
    OTHER = 15,
};
