# generated by zon2nix (https://github.com/nix-community/zon2nix)

{ linkFarm, fetchzip, fetchgit }:

linkFarm "zig-packages" [
  {
    name = "sdl-0.4.0+3.4.0-SDL--rq2owEZsySGuHCuVJ9naEvH3i3e_pyUIjziBtJ-";
    path = fetchgit {
      url = "https://github.com/castholm/SDL.git";
      rev = "887fa805e40d5c7bb3955ae69b89ed566c6a0471";
      hash = "sha256-AsOlMECtTVp+WRyrbjSh4hVozJKz1924B5dHf80/eIw=";
    };
  }
  {
    name = "sdl_linux_deps-0.0.0-SDL_ltg8hgAOayMwFN6BhHW3Rs5UPtf6n8m-2qcQHuGS";
    path = fetchgit {
      url = "https://github.com/castholm/SDL_linux_deps.git";
      rev = "fd349940b9dbaa0f221703b05df826d745d7ce2a";
      hash = "sha256-sgaGfevW0iUweBYFlce749UERP3j56wj32YMp6Kl4lw=";
    };
  }
]
